# Generated by Django 3.1.1 on 2020-09-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='civil',
            field=models.CharField(choices=[('Seul(e)', 'Seul(e)'), ('Marié(e)', 'Marié(e)'), ('Colocation', 'Colication'), ('Avec Enfant(s)', 'Avec Enfant(s)'), ('Personne(s) agée(s) à charge', 'Personne(s) agée(s) à charge')], default=0, max_length=120),
            preserve_default=False,
        ),
    ]
