# Generated by Django 3.1.1 on 2020-09-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_participants_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='syptomes',
            field=models.CharField(choices=[('fievre', 'fiévre(temperature>37.8°C)'), ('respiratoire', 'toux ou difficulté respiratoire'), ('diarrhe', 'diarrhée (au moins 3selles molles/j)'), ('cephalees', 'céphalées (maux de tête)'), ('douleurs', 'douleurs musculaires et courbatures'), ('odorat', "perte de l'odorat"), ('appetit', "perte de l'appétit"), ('fatigue', 'fatigue inhabituelle'), ('sympt', 'Pas de symptômes')], default=0, max_length=120),
            preserve_default=False,
        ),
    ]
