# Generated by Django 3.1.1 on 2020-09-13 22:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0003_participants_syptomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='syptomes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('fievre', 'fiévre(temperature>37.8°C)'), ('respiratoire', 'toux ou difficulté respiratoire'), ('diarrhe', 'diarrhée (au moins 3selles molles/j)'), ('cephalees', 'céphalées (maux de tête)'), ('douleurs', 'douleurs musculaires et courbatures'), ('odorat', "perte de l'odorat"), ('appetit', "perte de l'appétit"), ('fatigue', 'fatigue inhabituelle'), ('sympt', 'Pas de symptômes')], max_length=75),
        ),
    ]
