# Generated by Django 3.1.1 on 2020-09-13 22:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0004_auto_20200913_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='antecedents',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('hypertension', 'hypertension mal équilibrée'), ('diabete', 'diabète'), ('maladieRespiratoire', 'maladie respiratoire'), ('renale', 'insuffisance rénale'), ('immunitaire', 'insuffisance immunitaire'), ('fumeur', 'fumeur'), ('rien', "Pas d'antécédents")], default=0, max_length=71),
            preserve_default=False,
        ),
    ]
