# Generated by Django 3.1.1 on 2020-09-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0005_participants_antecedents'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='contact',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participants',
            name='etranger',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participants',
            name='voyage',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participants',
            name='civil',
            field=models.CharField(choices=[('Seul(e)', 'Seul(e)'), ('Marié(e)', 'Marié(e)'), ('Colocation', 'Colocation'), ('Avec Enfant(s)', 'Avec Enfant(s)'), ('Personne(s) agée(s) à charge', 'Personne(s) agée(s) à charge')], max_length=120),
        ),
    ]
