# Generated by Django 3.1.1 on 2020-09-14 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0006_auto_20200914_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='syptomes',
            new_name='symptomes',
        ),
    ]
