# Generated by Django 3.1.1 on 2020-09-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0007_auto_20200914_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='score',
            field=models.CharField(default='', max_length=20),
        ),
    ]
